name: CI/CD Deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy: 
    name: Deploy to Cloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code 
        uses: actions/checkout@v4
